blogTitle = "My Awesome Blog"
authorName = "Cole Townsend"
linkPrefix = "/"
intro = "Cole Townsend is a designer who wants to work with you. He has a penchant for thoughful solutions. Currently, he works at thoughbot in Boston. Let's make something excellent."
