blogTitle = "Portfolio of Cole Townsend"
authorName = "Cole Townsend"
linkPrefix = "/gatsby-starter-blog"
intro = "Cole Townsend is a designer who wants to work with you. He has a penchant for thoughful solutions. Currently, he works at thoughbot in Boston. Let's make something excellent."
