WorkList = [{
  title: 'Panda Courses',
  client: 'Panda',
  type: 'Web Design & Development',
  titleColor: 'white',
  date: '08 2015',
  published: 'false',
  classes: 'yellow-bg smaller',
  what: 'Learn to code from designers.',
  info: 'Tell designers about a new way to learn code, from designers.',
  challenge: 'Create and code an engaging and high converting landing page.',
  template: "panda-courses",
  logo: 'panda',
  thumbFile: 'gif',
  credits: "false"
}, {
  title: 'Meta Landing Page',
  client: 'Meta',
  template: "meta-landing-page",
  showTitle: "false",
  type: 'Web Design & Development',
  date: '08 2015',
  published: 'true',
  classes: 'blush-bg bigger',
  what: 'Illustrate how Meta will save everyone 4 hours a week.',
  info: 'Save everyone 4 hours a week',
  challenge: 'Create and code an engaging and high converting landing page for Meta Search.',
  logo: 'false',
  link: 'meta.sc',
  bg: "meta-lander-bg@2x.png",
  thumbFile: 'gif',
  credits: "false"
}, {
  title: 'Panda Jobs',
  client: 'Panda',
  type: 'Web Design',
  titleColor: 'white',
  date: '06 2015',
  published: 'false',
  classes: 'cyan-bg smaller',
  what: 'A job board made for designers.',
  info: 'Make Finding a Better Job, Better',
  challenge: 'Help job seekers find the job they love most.',
  template: "panda-jobs",
  link: "false",
  logo: 'panda',
  credits: "false"
}, {
  title: 'Startup Book List',
  titleColor: 'white',
  client: 'Panda',
  titleColor: 'white',
  date: '04 2015',
  type: 'Web Design',
  published: 'false',
  classes: 'blush-bg smaller',
  info: 'Find out what\'s on Ryan Hoover\'s Book Shelf',
  challenge: 'Create a cutting edge way to show off famous entreprenuers\' book suggestions.',
  template: "startup-book-list",
  bg: "",
  link: "false",
  logo: 'panda'
}, {
  title: 'Startup Launch List',
  client: 'Panda',
  titleColor: 'white',
  date: '03 2015',
  type: 'Web Design',
  published: 'true',
  classes: 'green-bg smaller',
  what: 'Get educated.',
  info: 'Design the Delightful Startup Launch List',
  challenge: 'Create a web app experience that helps people conquer large reading lists.',
  template: "startup-launch-list",
  bg: "startup-launch-list-bg-min.jpg",
  logo: 'panda',
  link: "www.startuplaunchlist.com",
  thumbFile: 'png',
}, {
  title: 'The Panda Network Site',
  client: 'Panda',
  titleColor: 'black',
  date: '01 2015',
  type: 'Web Design',
  published: 'true',
  classes: 'cyan-bg smaller',
  what: 'Get educated.',
  info: 'Craft a Presence for Panda Network',
  challenge: 'Show off Panda Network\'s prowess and attract new collaborators.',
  credits: "Ahmet Sulek for a delightful implementation and improvisation.",
  template: "panda-network",
  showTitle: "false",
  logo: "false",
  link: "panda.network",
  bg: "panda-network-bg-min.jpg",
  thumbFile: 'png'
}, {
  title: 'Goodrich Swipes',
  type: 'iOS Design',
  published: 'false',
  date: '10 2014',
  classes: 'blush-bg bigger',
  client: 'Goodrich Coffee',
  what: 'Order up!',
  info: 'Calm the Coffee Order Chaos',
  challenge: 'Speed up and organize Goodrich Coffee Bar orders.',
  template: "goodrich-swipes",
  logo: "false",
  showTitle: "false",
  bg: "gc-swipes-bg-min.png",
  thumbFile: 'png',
  link: "false"

}, {
  title: 'TheNews App for iOS',
  client: 'Panda',
  type: 'iOS Design',
  date: '10 2014',
  published: 'true',
  classes: 'lavender-bg bigger',
  what: 'Feeds at your fingertips',
  info: 'Feeds at your fingertips',
  challenge: 'Create a native iOS experience for TheNews.',
  credits: "Tosin Afolabi for crushing code.",
  template: "thenews",
  logo: 'false',
  link: "tosinaf.github.io/thenews/",
  showTitle: "false",
  bg: "thenews-app-bg.png",
  thumbFile: 'png'
}, ];
