WorkList = [ {
  title: 'Panda Jobs',
  client: 'Panda',
  type: 'Web Design',
  titleColor: 'white',
  date: '06 2015',
  published: 'false',
  classes: 'cyan-bg full',
  what: 'A job board made for designers.',
  info: 'Make Finding a Better Job, Better',
  challenge: 'Help job seekers find the job they love most.',
  template: "panda-jobs",
  logo: 'panda'
}, {
  title: 'Startup Book List',
  titleColor: 'white',
  client: 'Panda',
  titleColor: 'white',
  date: '04 2015',
  type: 'Web Design',
  published: 'false',
  classes: 'blush-bg bigger',
  info: 'What\'s on Ryan Hoover\'s Book Shelf?',
  challenge: 'Create a cutting edge way to show off famous entreprenuers\' book suggestions.',
  template: "startup-book-list",
  bg: "",
  logo: 'panda'
}, {
  title: 'Startup Launch List',
  client: 'Panda',
  titleColor: 'white',
  date: '03 2015',
  type: 'Web Design',
  published: 'true',
  classes: 'green-bg bigger',
  what: 'Get educated.',
  info: 'Design the Delightful Startup Launch List',
  challenge: 'Create a web app experience that helps people conquer large reading lists.',
  template: "startup-launch-list",
  logo: 'panda',
  thumbFile: 'jpg'
}, {
  title: 'The Panda Network Site',
  client: 'Panda',
  titleColor: 'black',
  date: '01 2015',
  type: 'Web Design',
  published: 'true',
  classes: 'cyan-bg smaller',
  what: 'Get educated.',
  info: 'Craft a Presence for Panda Network',
  challenge: 'Show off Panda Networks prowess and attract new collaborators.',
  template: "panda-network",
  logo: 'panda',
  thumbFile: 'png'
}, {
  title: 'Goodrich Swipes',
  type: 'iOS Design',
  published: 'true',
  date: '10 2014',
  classes: 'pink-bg smaller',
  client: 'Goodrich Coffee',
  what: 'Order up!',
  info: 'Calm the Coffee Order Chaos',
  template: "goodrich-swipes",
  bg: "gc-swipes-bg.png",
  thumbFile: 'jpg'

}, {
  title: 'TheNews App for iOS',
  client: 'Panda',
  type: 'iOS Design',
  date: '10 2014',
  published: 'true',
  classes: 'indigo-bg bigger',
  what: 'Feeds on swipe.',
  info: 'Make TheNews App Native',
  template: "thenews",
  logo: 'panda',
  thumbFile: 'jpg'
}, ];
